#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "[Husky] Pre Commit Hook - Linting Staged Files....\n\r";

echo "\n\r[Test] Pre Commit Hook \n\r";

yarn react-scripts test --bail --watchAll=false --passWithNoTests

echo "\n\r[Test Coverage] Pre Commit Hook \n\r";

yarn react-scripts test --bail --coverage --watchAll=false --passWithNoTests

echo "\n\r[E2E Cypress Coverage] Pre Commit Hook \n\r";

yarn start 2> /dev/null &
yarn cy:run

echo "\n\r[Code Lint] Pre Commit Hook \n\r";

yarn run lint-staged